apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: defid
  name: defid-indexer-docker
  labels:
    app.kubernetes.io/name: defid-indexer-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: defid-indexer-docker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: defid-indexer-docker
    spec:
      containers:
        - name: defid-indexer-docker
          image: muirglacier/defid-indexer:latest
          env:
            - name: OPR_ENV
              value: debug
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: USER
                  optional: false
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: PASS
                  optional: false
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: HOST
                  optional: false
            - name: MONGODB
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: MONGODB
                  optional: false
