apiVersion: v1
kind: Pod
metadata:
  name: defid-indexer-docker
  namespace: defid
  labels:
    app.kubernetes.io/name: defid-indexer-docker
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - defilense.com
  containers:
    env:
      - name: USER
        valueFrom:
          secretKeyRef:
            name: indexer-secret
            key: USER
            optional: false 
      - name: PASS
        valueFrom:
          secretKeyRef:
            name: indexer-secret
            key: PASS
            optional: false
      - name: HOST
        valueFrom:
          secretKeyRef:
            name: indexer-secret
            key: HOST
            optional: false 
      - name: MONGODB
        valueFrom:
          secretKeyRef:
            name: indexer-secret
            key: MONGODB
            optional: false 
    - name: defid-indexer-docker
      image: muirglacier/defid-indexer:latest
